ALTER TYPE "CooperativeType" ADD VALUE IF NOT EXISTS 'AHORRO_CREDITO';
ALTER TYPE "CooperativeType" ADD VALUE IF NOT EXISTS 'MOVIMIENTO_COOPERATIVO';
ALTER TYPE "CooperativeType" ADD VALUE IF NOT EXISTS 'TIPOS_DIVERSOS';
